// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PruebaaspContext))]
    [Migration("20260622090055_AddGestoDetalleAndMedia")]
    partial class AddGestoDetalleAndMedia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("MySql:Engine", "InnoDB")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Aparato", b =>
                {
                    b.Property<int>("sk_aparato_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_aparato_id"));

                    b.Property<DateTime?>("fecha_sincronizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_sincronizacion");

                    b.Property<string>("icono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icono");

                    b.Property<string>("nombre_aparato")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_aparato");

                    b.Property<int?>("sk_aparato_accion_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_accion_id");

                    b.Property<int?>("sk_aparato_tipo_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_tipo_id");

                    b.Property<int?>("sk_usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    b.HasKey("sk_aparato_id");

                    b.HasIndex("sk_aparato_accion_id");

                    b.HasIndex("sk_aparato_tipo_id");

                    b.HasIndex("sk_usuario_id");

                    b.ToTable("aparato", (string)null);
                });

            modelBuilder.Entity("backend.Models.AparatoAccion", b =>
                {
                    b.Property<int>("sk_aparato_accion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_accion_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_aparato_accion_id"));

                    b.Property<string>("accion_nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("accion_nombre");

                    b.Property<string>("comando_bluetooth")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comando_bluetooth");

                    b.HasKey("sk_aparato_accion_id");

                    b.HasIndex("accion_nombre", "comando_bluetooth")
                        .IsUnique();

                    b.ToTable("aparato_accion", (string)null);
                });

            modelBuilder.Entity("backend.Models.AparatoBluetooth", b =>
                {
                    b.Property<int>("sk_aparato_bluetooth_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_bluetooth_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_aparato_bluetooth_id"));

                    b.Property<string>("mac_bluetooth")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("mac_bluetooth");

                    b.Property<string>("nombre_bluetooth")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_bluetooth");

                    b.Property<int>("sk_aparato_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_id");

                    b.HasKey("sk_aparato_bluetooth_id");

                    b.HasIndex("sk_aparato_id")
                        .IsUnique();

                    b.ToTable("aparato_bluetooth", (string)null);
                });

            modelBuilder.Entity("backend.Models.AparatoConfiguracionRed", b =>
                {
                    b.Property<int>("sk_aparato_configuracion_red_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_configuracion_red_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_aparato_configuracion_red_id"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("device_key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_key");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("fecha_ultima_conexion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ultima_conexion");

                    b.Property<string>("host_name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("host_name");

                    b.Property<string>("ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("mac_address")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("mac_address");

                    b.Property<string>("protocolo_socket")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("protocolo_socket");

                    b.Property<int?>("puerto_socket")
                        .HasColumnType("int")
                        .HasColumnName("puerto_socket");

                    b.Property<string>("ruta_socket")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ruta_socket");

                    b.Property<int>("sk_aparato_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_id");

                    b.HasKey("sk_aparato_configuracion_red_id");

                    b.HasIndex("device_key")
                        .IsUnique();

                    b.HasIndex("sk_aparato_id")
                        .IsUnique();

                    b.ToTable("aparato_configuracion_red", (string)null);
                });

            modelBuilder.Entity("backend.Models.AparatoControl", b =>
                {
                    b.Property<int>("sk_aparato_control_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_control_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_aparato_control_id"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("comando_socket")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("comando_socket");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("sk_aparato_controlado_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_controlado_id");

                    b.Property<int>("sk_aparato_controlador_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_controlador_id");

                    b.HasKey("sk_aparato_control_id");

                    b.HasIndex("sk_aparato_controlado_id");

                    b.HasIndex("sk_aparato_controlador_id", "sk_aparato_controlado_id")
                        .IsUnique();

                    b.ToTable("aparato_control", (string)null);
                });

            modelBuilder.Entity("backend.Models.AparatoTipo", b =>
                {
                    b.Property<int>("sk_aparato_tipo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_tipo_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_aparato_tipo_id"));

                    b.Property<bool>("es_asistente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("es_asistente");

                    b.Property<string>("icono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icono");

                    b.Property<string>("nombre_tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_tipo");

                    b.Property<string>("palabras_clave_busqueda")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("soporta_bluetooth")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("soporta_wifi")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("sk_aparato_tipo_id");

                    b.HasIndex("nombre_tipo")
                        .IsUnique();

                    b.ToTable("aparato_tipo", (string)null);
                });

            modelBuilder.Entity("backend.Models.Gesto", b =>
                {
                    b.Property<int>("sk_gesto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_gesto_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_gesto_id"));

                    b.Property<int>("bk_gesto_id")
                        .HasColumnType("int")
                        .HasColumnName("bk_gesto_id");

                    b.Property<string>("icono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("identificador_ia")
                        .HasColumnType("int")
                        .HasColumnName("identificador_ia");

                    b.Property<decimal>("nivel_confianza_minimo")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("nivel_confianza_minimo");

                    b.Property<string>("nombre_gesto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_gesto");

                    b.Property<int?>("sk_aparato_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_id");

                    b.Property<int?>("sk_usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    b.Property<string>("tipo_disparador_nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_disparador_nombre");

                    b.HasKey("sk_gesto_id");

                    b.HasIndex("sk_aparato_id");

                    b.HasIndex("sk_usuario_id");

                    b.ToTable("gesto", (string)null);
                });

            modelBuilder.Entity("backend.Models.GestoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_gesto_detalle_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DistanciaRecomendada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("distancia_recomendada");

                    b.Property<decimal>("DuracionSegundos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("duracion_segundos");

                    b.Property<int>("GestoId")
                        .HasColumnType("int")
                        .HasColumnName("sk_gesto_id");

                    b.Property<string>("IluminacionRecomendada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("iluminacion_recomendada");

                    b.HasKey("Id");

                    b.HasIndex("GestoId")
                        .IsUnique();

                    b.ToTable("gesto_detalle", (string)null);
                });

            modelBuilder.Entity("backend.Models.GestoMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_media_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Extension")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("extension");

                    b.Property<int>("GestoDetalleId")
                        .HasColumnType("int")
                        .HasColumnName("sk_gesto_detalle_id");

                    b.Property<int>("TipoMedia")
                        .HasColumnType("int")
                        .HasColumnName("tipo_media");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url_archivo");

                    b.HasKey("Id");

                    b.HasIndex("GestoDetalleId");

                    b.ToTable("gesto_media", (string)null);
                });

            modelBuilder.Entity("backend.Models.HistorialActividad", b =>
                {
                    b.Property<int>("sk_actividad_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_actividad_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_actividad_id"));

                    b.Property<decimal>("confianza_ia")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("confianza_ia");

                    b.Property<bool>("ejecucion_exitosa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ejecucion_exitosa");

                    b.Property<int>("sk_aparato_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_id");

                    b.Property<int>("sk_gesto_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_gesto_id");

                    b.Property<int>("sk_tiempo_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_tiempo_id");

                    b.Property<int>("sk_usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    b.Property<int>("tiempo_respuesta")
                        .HasColumnType("int")
                        .HasColumnName("tiempo_respuesta");

                    b.HasKey("sk_actividad_id");

                    b.HasIndex("sk_aparato_id");

                    b.HasIndex("sk_gesto_id");

                    b.HasIndex("sk_tiempo_id");

                    b.HasIndex("sk_usuario_id");

                    b.ToTable("historial_actividad", (string)null);
                });

            modelBuilder.Entity("backend.Models.Tiempo", b =>
                {
                    b.Property<int>("sk_tiempo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_tiempo_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_tiempo_id"));

                    b.Property<int>("anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<string>("dia_semana_nombre")
                        .HasColumnType("longtext")
                        .HasColumnName("dia_semana_nombre");

                    b.Property<DateOnly>("fecha_completa")
                        .HasColumnType("date")
                        .HasColumnName("fecha_completa");

                    b.Property<int>("hora_periodo")
                        .HasColumnType("int")
                        .HasColumnName("hora_periodo");

                    b.Property<string>("mes_nombre")
                        .HasColumnType("longtext")
                        .HasColumnName("mes_nombre");

                    b.Property<int>("mes_numero")
                        .HasColumnType("int")
                        .HasColumnName("mes_numero");

                    b.HasKey("sk_tiempo_id");

                    b.ToTable("tiempo", (string)null);
                });

            modelBuilder.Entity("backend.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Cadena")
                        .HasColumnType("longtext")
                        .HasColumnName("cadena");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<int>("sk_usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("sk_usuario_id");

                    b.ToTable("token", (string)null);
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<int>("sk_usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_usuario_id"));

                    b.Property<string>("contrasenia")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("email_usuario")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email_usuario");

                    b.Property<string>("mac_address_usuario")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("mac_address_usuario");

                    b.Property<string>("nombre_arduino")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_arduino");

                    b.Property<string>("nombre_usuario")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("sk_usuario_id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("backend.Models.Aparato", b =>
                {
                    b.HasOne("backend.Models.AparatoAccion", "Accion")
                        .WithMany("Aparatos")
                        .HasForeignKey("sk_aparato_accion_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.AparatoTipo", "Tipo")
                        .WithMany("Aparatos")
                        .HasForeignKey("sk_aparato_tipo_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Aparatos")
                        .HasForeignKey("sk_usuario_id");

                    b.Navigation("Accion");

                    b.Navigation("Tipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.AparatoBluetooth", b =>
                {
                    b.HasOne("backend.Models.Aparato", "Aparato")
                        .WithOne("Bluetooth")
                        .HasForeignKey("backend.Models.AparatoBluetooth", "sk_aparato_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aparato");
                });

            modelBuilder.Entity("backend.Models.AparatoConfiguracionRed", b =>
                {
                    b.HasOne("backend.Models.Aparato", "Aparato")
                        .WithOne("ConfiguracionRed")
                        .HasForeignKey("backend.Models.AparatoConfiguracionRed", "sk_aparato_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aparato");
                });

            modelBuilder.Entity("backend.Models.AparatoControl", b =>
                {
                    b.HasOne("backend.Models.Aparato", "Controlado")
                        .WithMany("Controladores")
                        .HasForeignKey("sk_aparato_controlado_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Aparato", "Controlador")
                        .WithMany("AparatosControlados")
                        .HasForeignKey("sk_aparato_controlador_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controlado");

                    b.Navigation("Controlador");
                });

            modelBuilder.Entity("backend.Models.Gesto", b =>
                {
                    b.HasOne("backend.Models.Aparato", "Aparato")
                        .WithMany("Gestos")
                        .HasForeignKey("sk_aparato_id");

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Gestos")
                        .HasForeignKey("sk_usuario_id");

                    b.Navigation("Aparato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.GestoDetalle", b =>
                {
                    b.HasOne("backend.Models.Gesto", "Gesto")
                        .WithOne()
                        .HasForeignKey("backend.Models.GestoDetalle", "GestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gesto");
                });

            modelBuilder.Entity("backend.Models.GestoMedia", b =>
                {
                    b.HasOne("backend.Models.GestoDetalle", "GestoDetalle")
                        .WithMany("MediosReferencia")
                        .HasForeignKey("GestoDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GestoDetalle");
                });

            modelBuilder.Entity("backend.Models.HistorialActividad", b =>
                {
                    b.HasOne("backend.Models.Aparato", "Aparato")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_aparato_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Gesto", "Gesto")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_gesto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Tiempo", "Tiempo")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_tiempo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aparato");

                    b.Navigation("Gesto");

                    b.Navigation("Tiempo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Token", b =>
                {
                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Tokens")
                        .HasForeignKey("sk_usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Aparato", b =>
                {
                    b.Navigation("AparatosControlados");

                    b.Navigation("Bluetooth");

                    b.Navigation("ConfiguracionRed");

                    b.Navigation("Controladores");

                    b.Navigation("Gestos");

                    b.Navigation("Historico_Actividad");
                });

            modelBuilder.Entity("backend.Models.AparatoAccion", b =>
                {
                    b.Navigation("Aparatos");
                });

            modelBuilder.Entity("backend.Models.AparatoTipo", b =>
                {
                    b.Navigation("Aparatos");
                });

            modelBuilder.Entity("backend.Models.Gesto", b =>
                {
                    b.Navigation("Historico_Actividad");
                });

            modelBuilder.Entity("backend.Models.GestoDetalle", b =>
                {
                    b.Navigation("MediosReferencia");
                });

            modelBuilder.Entity("backend.Models.Tiempo", b =>
                {
                    b.Navigation("Historico_Actividad");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Navigation("Aparatos");

                    b.Navigation("Gestos");

                    b.Navigation("Historico_Actividad");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
