// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PruebaaspContext))]
    [Migration("20260604053452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Aparato", b =>
                {
                    b.Property<int>("sk_aparato_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_aparato_id"));

                    b.Property<string>("accion_nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("accion_nombre");

                    b.Property<string>("comando_bluetooth")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comando_bluetooth");

                    b.Property<DateTime?>("fecha_sincronizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_sincronizacion");

                    b.Property<string>("icono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icono");

                    b.Property<string>("mac_bluetooth")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("mac_bluetooth");

                    b.Property<string>("nombre_aparato")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_aparato");

                    b.Property<string>("nombre_bluetooth")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_bluetooth");

                    b.Property<int?>("sk_usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    b.Property<string>("tipo_aparato")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_aparato");

                    b.HasKey("sk_aparato_id");

                    b.HasIndex("sk_usuario_id");

                    b.ToTable("aparato", (string)null);
                });

            modelBuilder.Entity("backend.Models.Esp32Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("esp32_device", (string)null);
                });

            modelBuilder.Entity("backend.Models.Esp32Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("longtext");

                    b.Property<string>("Response")
                        .HasColumnType("longtext");

                    b.Property<int>("SourceDeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetDeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("WasProcessed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SourceDeviceId");

                    b.HasIndex("TargetDeviceId");

                    b.ToTable("esp32_message", (string)null);
                });

            modelBuilder.Entity("backend.Models.Gesto", b =>
                {
                    b.Property<int>("sk_gesto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_gesto_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_gesto_id"));

                    b.Property<int>("bk_gesto_id")
                        .HasColumnType("int")
                        .HasColumnName("bk_gesto_id");

                    b.Property<int>("identificador_ia")
                        .HasColumnType("int")
                        .HasColumnName("identificador_ia");

                    b.Property<decimal>("nivel_confianza_minimo")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("nivel_confianza_minimo");

                    b.Property<string>("nombre_gesto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_gesto");

                    b.Property<int?>("sk_aparato_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_id");

                    b.Property<int?>("sk_usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    b.Property<string>("tipo_disparador_nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_disparador_nombre");

                    b.HasKey("sk_gesto_id");

                    b.HasIndex("sk_aparato_id");

                    b.HasIndex("sk_usuario_id");

                    b.ToTable("gesto", (string)null);
                });

            modelBuilder.Entity("backend.Models.HistorialActividad", b =>
                {
                    b.Property<int>("sk_actividad_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_actividad_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_actividad_id"));

                    b.Property<decimal>("confianza_ia")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("confianza_ia");

                    b.Property<bool>("ejecucion_exitosa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ejecucion_exitosa");

                    b.Property<int>("sk_aparato_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_aparato_id");

                    b.Property<int>("sk_gesto_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_gesto_id");

                    b.Property<int>("sk_tiempo_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_tiempo_id");

                    b.Property<int>("sk_usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    b.Property<int>("tiempo_respuesta")
                        .HasColumnType("int")
                        .HasColumnName("tiempo_respuesta");

                    b.HasKey("sk_actividad_id");

                    b.HasIndex("sk_aparato_id");

                    b.HasIndex("sk_gesto_id");

                    b.HasIndex("sk_tiempo_id");

                    b.HasIndex("sk_usuario_id");

                    b.ToTable("historial_actividad", (string)null);
                });

            modelBuilder.Entity("backend.Models.Tiempo", b =>
                {
                    b.Property<int>("sk_tiempo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_tiempo_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_tiempo_id"));

                    b.Property<int>("anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<string>("dia_semana_nombre")
                        .HasColumnType("longtext")
                        .HasColumnName("dia_semana_nombre");

                    b.Property<DateOnly>("fecha_completa")
                        .HasColumnType("date")
                        .HasColumnName("fecha_completa");

                    b.Property<int>("hora_periodo")
                        .HasColumnType("int")
                        .HasColumnName("hora_periodo");

                    b.Property<string>("mes_nombre")
                        .HasColumnType("longtext")
                        .HasColumnName("mes_nombre");

                    b.Property<int>("mes_numero")
                        .HasColumnType("int")
                        .HasColumnName("mes_numero");

                    b.HasKey("sk_tiempo_id");

                    b.ToTable("tiempo", (string)null);
                });

            modelBuilder.Entity("backend.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Cadena")
                        .HasColumnType("longtext")
                        .HasColumnName("cadena");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<int>("sk_usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("sk_usuario_id");

                    b.ToTable("token", (string)null);
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<int>("sk_usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_usuario_id"));

                    b.Property<string>("contrasenia")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("email_usuario")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email_usuario");

                    b.Property<string>("mac_address_usuario")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("mac_address_usuario");

                    b.Property<string>("nombre_arduino")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_arduino");

                    b.Property<string>("nombre_usuario")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("sk_usuario_id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("backend.Models.Aparato", b =>
                {
                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Aparatos")
                        .HasForeignKey("sk_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Esp32Message", b =>
                {
                    b.HasOne("backend.Models.Esp32Device", "SourceDevice")
                        .WithMany("SentMessages")
                        .HasForeignKey("SourceDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Esp32Device", "TargetDevice")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("TargetDeviceId");

                    b.Navigation("SourceDevice");

                    b.Navigation("TargetDevice");
                });

            modelBuilder.Entity("backend.Models.Gesto", b =>
                {
                    b.HasOne("backend.Models.Aparato", "Aparato")
                        .WithMany("Gestos")
                        .HasForeignKey("sk_aparato_id");

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Gestos")
                        .HasForeignKey("sk_usuario_id");

                    b.Navigation("Aparato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.HistorialActividad", b =>
                {
                    b.HasOne("backend.Models.Aparato", "Aparato")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_aparato_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Gesto", "Gesto")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_gesto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Tiempo", "Tiempo")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_tiempo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aparato");

                    b.Navigation("Gesto");

                    b.Navigation("Tiempo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Token", b =>
                {
                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Tokens")
                        .HasForeignKey("sk_usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Aparato", b =>
                {
                    b.Navigation("Gestos");

                    b.Navigation("Historico_Actividad");
                });

            modelBuilder.Entity("backend.Models.Esp32Device", b =>
                {
                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("backend.Models.Gesto", b =>
                {
                    b.Navigation("Historico_Actividad");
                });

            modelBuilder.Entity("backend.Models.Tiempo", b =>
                {
                    b.Navigation("Historico_Actividad");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Navigation("Aparatos");

                    b.Navigation("Gestos");

                    b.Navigation("Historico_Actividad");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
