// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PruebaaspContext))]
    [Migration("20260701120000_AddEsp32EstadoYMensajes")]
    partial class AddEsp32EstadoYMensajes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is maintained in PruebaaspContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
