// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PruebaaspContext))]
    [Migration("20260602195317_AgregarESP32")]
    partial class AgregarESP32
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Dim_Aparatos", b =>
                {
                    b.Property<int>("sk_aparato_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_aparato_id"));

                    b.Property<string>("accion_nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("comando_bluetooth")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("icono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("nombre_aparato")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tipo_aparato")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("sk_aparato_id");

                    b.ToTable("Dim_Aparato");
                });

            modelBuilder.Entity("backend.Models.Dim_Gestos", b =>
                {
                    b.Property<int>("sk_gesto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_gesto_id"));

                    b.Property<int>("bk_gesto_id")
                        .HasColumnType("int");

                    b.Property<int>("identificador_ia")
                        .HasColumnType("int");

                    b.Property<decimal>("nivel_confianza_minimo")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("nombre_gesto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tipo_disparador_nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("sk_gesto_id");

                    b.ToTable("Dim_Gesto");
                });

            modelBuilder.Entity("backend.Models.Dim_Tiempo", b =>
                {
                    b.Property<int>("sk_tiempo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_tiempo_id"));

                    b.Property<int>("anio")
                        .HasColumnType("int");

                    b.Property<string>("dia_semana_nombre")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("fecha_completa")
                        .HasColumnType("date");

                    b.Property<int>("hora_periodo")
                        .HasColumnType("int");

                    b.Property<string>("mes_nombre")
                        .HasColumnType("longtext");

                    b.Property<int>("mes_numero")
                        .HasColumnType("int");

                    b.HasKey("sk_tiempo_id");

                    b.ToTable("Dim_Tiempo");
                });

            modelBuilder.Entity("backend.Models.Dim_Usuarios", b =>
                {
                    b.Property<int>("sk_usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sk_usuario_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_usuario_id"));

                    b.Property<string>("contrasenia")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("email_usuario")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email_usuario");

                    b.Property<string>("mac_address_usuario")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("mac_address_usuario");

                    b.Property<string>("nombre_arduino")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_arduino");

                    b.Property<string>("nombre_usuario")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("sk_usuario_id");

                    b.ToTable("dim_usuario", (string)null);
                });

            modelBuilder.Entity("backend.Models.Esp32Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Esp32Device");
                });

            modelBuilder.Entity("backend.Models.Esp32Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("longtext");

                    b.Property<string>("Response")
                        .HasColumnType("longtext");

                    b.Property<int>("SourceDeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetDeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("WasProcessed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SourceDeviceId");

                    b.HasIndex("TargetDeviceId");

                    b.ToTable("Esp32Message");
                });

            modelBuilder.Entity("backend.Models.Fact_Historico_Actividad", b =>
                {
                    b.Property<int>("sk_actividad_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sk_actividad_id"));

                    b.Property<decimal>("confianza_ia")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("ejecucion_exitosa")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("sk_aparato_id")
                        .HasColumnType("int");

                    b.Property<int>("sk_gesto_id")
                        .HasColumnType("int");

                    b.Property<int>("sk_tiempo_id")
                        .HasColumnType("int");

                    b.Property<int>("sk_usuario_id")
                        .HasColumnType("int");

                    b.Property<int>("tiempo_respuesta")
                        .HasColumnType("int");

                    b.HasKey("sk_actividad_id");

                    b.HasIndex("sk_aparato_id");

                    b.HasIndex("sk_gesto_id");

                    b.HasIndex("sk_tiempo_id");

                    b.HasIndex("sk_usuario_id");

                    b.ToTable("Historico_Actividad");
                });

            modelBuilder.Entity("backend.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cadena")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("sk_usuario_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("sk_usuario_id");

                    b.ToTable("token", (string)null);
                });

            modelBuilder.Entity("backend.Models.Esp32Message", b =>
                {
                    b.HasOne("backend.Models.Esp32Device", "SourceDevice")
                        .WithMany("SentMessages")
                        .HasForeignKey("SourceDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Esp32Device", "TargetDevice")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("TargetDeviceId");

                    b.Navigation("SourceDevice");

                    b.Navigation("TargetDevice");
                });

            modelBuilder.Entity("backend.Models.Fact_Historico_Actividad", b =>
                {
                    b.HasOne("backend.Models.Dim_Aparatos", "Dim_Aparato")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_aparato_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Dim_Gestos", "Dim_Gesto")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_gesto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Dim_Tiempo", "Dim_Tiempo")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_tiempo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Dim_Usuarios", "Dim_Usuario")
                        .WithMany("Historico_Actividad")
                        .HasForeignKey("sk_usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dim_Aparato");

                    b.Navigation("Dim_Gesto");

                    b.Navigation("Dim_Tiempo");

                    b.Navigation("Dim_Usuario");
                });

            modelBuilder.Entity("backend.Models.Token", b =>
                {
                    b.HasOne("backend.Models.Dim_Usuarios", "Usuario")
                        .WithMany("Tokens")
                        .HasForeignKey("sk_usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Dim_Aparatos", b =>
                {
                    b.Navigation("Historico_Actividad");
                });

            modelBuilder.Entity("backend.Models.Dim_Gestos", b =>
                {
                    b.Navigation("Historico_Actividad");
                });

            modelBuilder.Entity("backend.Models.Dim_Tiempo", b =>
                {
                    b.Navigation("Historico_Actividad");
                });

            modelBuilder.Entity("backend.Models.Dim_Usuarios", b =>
                {
                    b.Navigation("Historico_Actividad");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("backend.Models.Esp32Device", b =>
                {
                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
