// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PruebaaspContext))]
    [Migration("20260702183000_AddConsumoHistorico")]
    partial class AddConsumoHistorico
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
#pragma warning restore 612, 618
        }
    }
}
